import type { Metadata } from 'next'
import { Toaster } from '@/components/ui/sonner'
import { SidebarProvider, SidebarTrigger } from '@/components/ui/sidebar'
import { AppSidebar } from '@/components/app-sidebar'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <>
      <Toaster richColors closeButton />
      <SidebarProvider>
        <AppSidebar />
        <main className="flex flex-col w-full h-screen overflow-hidden">
          <SidebarTrigger />
          {children}
        </main>
      </SidebarProvider>
    </>
  )
}
